#!/bin/bash
# SSH密钥部署指南

echo "========================================"
echo "🔐 SSH密钥部署指南"
echo "========================================"
echo ""
echo "✅ SSH密钥已生成！"
echo ""
echo "📋 公钥内容 (请复制下面全部内容):"
echo ""
cat ~/.ssh/id_ed25519.pub
echo ""
echo "========================================"
echo ""
echo "步骤1: 添加公钥到GitHub"
echo ""
echo "1. 访问: https://github.com/settings/keys"
echo "2. 点击: New SSH key"
echo "3. 标题: Nexus AI Deployment"
echo "4. 粘贴上面的公钥内容"
echo "5. 点击: Add SSH key"
echo ""
echo "========================================"
echo ""
echo "步骤2: 切换为SSH连接"
echo ""
echo "运行命令:"
echo "  cd ~/.openclaw/workspace/company_system"
echo "  git remote set-url origin git@github.com:maoshuorz/nexus-ai.git"
echo ""
echo "========================================"
echo ""
echo "步骤3: 推送代码"
echo ""
echo "运行命令:"
echo "  git push -u origin main"
echo ""
echo "(第一次连接会提示确认，输入 yes 回车)"
echo ""
echo "========================================"
echo ""
echo "步骤4: 启用GitHub Pages"
echo ""
echo "访问: https://github.com/maoshuorz/nexus-ai/settings/pages"
echo "Source: Deploy from a branch"
echo "Branch: main / (root)"
echo "点击 Save"
echo ""
echo "========================================"
echo "✅ 完成后，网站地址:"
echo "   https://maoshuorz.github.io/nexus-ai/"
echo "========================================"
